module.exports = {
   LatestShipDate: 'LatestShipDate',
   OrderType: 'OrderType',
   PurchaseDate: 'PurchaseDate',
   AmazonOrderId: 'AmazonOrderId',
   IsReplacementOrder: 'IsReplacementOrder',
   NumberOfItemsShipped: 'NumberOfItemsShipped',
   ShipServiceLevel: 'ShipServiceLevel',
   BuyerName: 'BuyerName',
   OrderTotal: 'OrderTotal',
   Amount: 'Amount',
   CurrencyCode: 'CurrencyCode',
   ShippingAddress: 'ShippingAddress',
   City: 'City',
   PostalCode: 'PostalCode',
   StateOrRegion: 'StateOrRegion',
   Name: 'Name',
   AddressLine1: 'AddressLine1',
   ShipmentServiceLevelxCategory: 'ShipmentServiceLevelCategory',
   isPrime: 'isPrime'
};
